name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - '**/*.py'
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: just install lint
